services:
  r7manga:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r7manga
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      AUTH_TRUST_HOST: "true"
    ports:
      - "3002:3000"
