import { ThemeProvider } from '@/components/theme-provider';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { HeadDemo } from '@/components/head_carouse';

import localFont from 'next/font/local';
import './globals.css';

import type { Metadata } from 'next';
import { Copyright } from 'lucide-react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <div className="flex flex-col flex-1">
              <div className="flex flex-col min-h-svh">
                <HeadDemo />
                {children}
              </div>
              <footer className="flex justify-center items-center gap-1 mt-10 select-none">
                <Copyright size={10} />
                <span>archie0732 manga</span>
              </footer>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>

    </html>
  );
}
